change conditions to execute

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,8 +3,6 @@ name: "php artisan test"
 on:
   pull_request:
     types: [opened, synchronize, reopened]
-  issue_comment:
-    types: [created]
 
 env:
   GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
@@ -13,12 +11,20 @@ env:
 jobs:
   build:
     name: "Run Test"
-    if: (github.event_name == 'pull_request' || github.event_name == 'issue_comment') && contains(github.event.comment.body, '/run-tests')
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
 
+      - name: Check if tests should be skipped
+        id: check_skip
+        run: |
+          if [ "${{ github.event.issue.pull_request }}" != "" ] && [[ "${{ github.event.comment.body }}" != *"/run-tests"* ]]; then
+            echo "Tests should be skipped."
+            exit 1
+          fi
+
       - name: dokcer-compose Laravel Init
+        if: steps.check_skip.outcome == 'success'
         run: |
           docker-compose up -d
           docker compose exec -T php-apache bash -c "composer install"
@@ -28,6 +34,7 @@ jobs:
           docker compose exec -T php-apache bash -c "sleep 200"
 
       - name: Exec Test
+        if: steps.check_skip.outcome == 'success'
         run: |
           # docker compose exec -T php-apache bash -c "phpdbg -qrr ./vendor/bin/phpunit --coverage-text --colors=never > storage/logs/coverage.log"
           # docker compose exec -T php-apache bash -c "cat storage/logs/coverage.log"
@@ -35,22 +42,26 @@ jobs:
           docker compose exec -T php-apache bash -c "cat storage/logs/coverage.log"
 
       - name: Cat Test Result
+        if: steps.check_skip.outcome == 'success'
         run: |
           cat ./web/storage/logs/coverage.log
         if: ${{ failure() }}
 
       - name: Sed Coverage Report
+        if: steps.check_skip.outcome == 'success'
         run: |
           sed -E "s/"$'\E'"\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" | \
           grep "Code Coverage Report:" -A6 ./web/storage/logs/coverage.log | sed -e "s/^ *//" | sed -e "s/ *$//" | sed -e "/^ *$/d" > ./web/storage/logs/coverage-summary.log
 
       - name: Read coverage summary
+        if: steps.check_skip.outcome == 'success'
         id: coverage-summary
         uses: juliangruber/read-file-action@v1
         with:
           path: ./web/storage/logs/coverage-summary.log
 
       - name: Comment Coverage Summary
+        if: steps.check_skip.outcome == 'success'
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: coverage-summary
@@ -62,8 +73,9 @@ jobs:
             ${{ steps.coverage-report-urls.outputs.content }}
 
       - name: Action Slack Notify
+        # Pick up events even if the job fails or is canceled.
+        if: always()
         uses: 8398a7/action-slack@v3
         with:
           status: ${{ job.status }}
           fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
-        if: always() # Pick up events even if the job fails or is canceled.
